version: '3.4'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    links:
      - fpm:docker-php-fpm
  fpm:
    build: .
    ports:
      - "9000"
    restart: always
    links:
      - mysql:docker-mysql
    volumes:
      - ./app:/var/www/html
  mysql:
    image: mysql:5.6
    ports:
      - "13306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./app/database:/data/database